### ISSUE TITLE
[Bug]: Docker images not yet updating 

### ISSUE THREAD

**Issue by saschafoerster** [josephdadams/TallyArbiter#659]
### What happened?

I was trying to upgrade to 3.0.8 via docker hub: 

```
version: '3.3'
services:
    tallyarbiter:
        ports:
            - '4455:4455'
        volumes:
            - /home/tallyarbiter/volume:/app/config
        environment:
            - APPDATA=/app/config
        restart: unless-stopped
        image: josephdadams/tallyarbiter:latest
```
Latest working version is 
`        image: josephdadams/tallyarbiter:v3.0.1`

Latest update on docker hub: 
https://hub.docker.com/r/josephdadams/tallyarbiter
2 years ago. 

Would be lovely if this could be fixed. :) 

### Version

3.0.8

### Distribution

Docker

### OS

Linux

### Relevant log output

```shell
tallyarbiter-1  | node:internal/modules/cjs/loader:936
tallyarbiter-1  |   throw err;
tallyarbiter-1  |   ^
tallyarbiter-1  | 
tallyarbiter-1  | Error: Cannot find module '/app/node_modules/bcrypt/lib/binding/napi-v3/bcrypt_lib.node'
tallyarbiter-1  | Require stack:
tallyarbiter-1  | - /app/node_modules/bcrypt/bcrypt.js
tallyarbiter-1  | - /app/_helpers/auth.js
tallyarbiter-1  | - /app/_helpers/config.js
tallyarbiter-1  | - /app/index.js
tallyarbiter-1  |     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
tallyarbiter-1  |     at Function.Module._load (node:internal/modules/cjs/loader:778:27)
tallyarbiter-1  |     at Module.require (node:internal/modules/cjs/loader:1005:19)
tallyarbiter-1  |     at require (node:internal/modules/cjs/helpers:102:18)
tallyarbiter-1  |     at Object.<anonymous> (/app/node_modules/bcrypt/bcrypt.js:6:16)
tallyarbiter-1  |     at Module._compile (node:internal/modules/cjs/loader:1103:14)
tallyarbiter-1  |     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1155:10)
tallyarbiter-1  |     at Module.load (node:internal/modules/cjs/loader:981:32)
tallyarbiter-1  |     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
tallyarbiter-1  |     at Module.require (node:internal/modules/cjs/loader:1005:19) {
tallyarbiter-1  |   code: 'MODULE_NOT_FOUND',
tallyarbiter-1  |   requireStack: [
tallyarbiter-1  |     '/app/node_modules/bcrypt/bcrypt.js',
tallyarbiter-1  |     '/app/_helpers/auth.js',
tallyarbiter-1  |     '/app/_helpers/config.js',
tallyarbiter-1  |     '/app/index.js'
tallyarbiter-1  |   ]
tallyarbiter-1  | }
tallyarbiter-1 exited with code 0
```
